(function(g){var window=this;var uua=function(a,b){return g.bc(a,b)},Y5=function(a,b,c){a.w.set(b,c)},Z5=function(a){Y5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.I)()).toString(36));
return a},$5=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.cn(a.w,b,c)},vua=function(a,b){var c=[];
g.jk(b,function(d){try{var e=g.fo.prototype.u.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.eo(e)&&c.push(d)},a);
return c},wua=function(a,b){var c=vua(a,b);
(0,g.y)(c,function(d){g.fo.prototype.remove.call(this,d)},a)},xua=function(a,b){g.cb(a,b)||a.push(b)},a6=function(a){var b=0,c;
for(c in a)b++;return b},yua=function(a,b){var c=b instanceof g.Cc?b:g.Gc(b,/^data:image\//i.test(b));
a.src=g.Dc(c)},b6=function(){},zua=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},Aua=function(a){if(a.Dd&&"function"==typeof a.Dd)return a.Dd();
if("string"===typeof a)return a.split("");if(g.Na(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Xb(a)},Bua=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Na(a)||"string"===typeof a)(0,g.y)(a,b,void 0);else{if(a.ye&&"function"==typeof a.ye)var c=a.ye();else if(a.Dd&&"function"==typeof a.Dd)c=void 0;else if(g.Na(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Yb(a);d=Aua(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},Cua=function(a,b,c,d){var e=new g.Rm(null,void 0);
a&&g.Sm(e,a);b&&g.Tm(e,b);c&&g.Um(e,c);d&&(e.u=d);return e},c6=function(a,b){g.Oo[a]=!0;
var c=g.Mo();c&&c.publish.apply(c,arguments);g.Oo[a]=!1},d6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.w=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Om;this.o=this.u="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",Dua(this,a.capabilities||""),Eua(this,a.experiments||""),this.u=a.remoteControllerUrl||"",this.o=a.localChannelEncryptionKey||
"")},Dua=function(a,b){a.capabilities.clear();
(0,g.ue)(b.split(","),g.Sa(uua,Fua)).forEach(function(c){a.capabilities.add(c)})},Eua=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},e6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},f6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},Gua=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},Hua=function(a){return new e6(a)},Iua=function(a){return g.Ma(a)?(0,g.A)(a,Hua):[]},g6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},h6=function(a){return g.Ma(a)?"["+(0,g.A)(a,g6).join(",")+"]":"null"},i6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},Jua=function(a){return(0,g.A)(a,function(b){return{key:b.id,
name:b.name}})},j6=function(a,b){return g.$a(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},k6=function(a,b){return g.$a(a,function(c){return f6(c,b)})},l6=function(a){try{var b=(0,g.ps)(),c=(0,g.os)();
b&&b.remove(a);c&&c.remove(a)}catch(d){}},Kua=function(){var a=(0,g.os)();
a&&wua(a,a.o.Of(!0))},m6=function(){var a=g.rs("yt-remote-connected-devices")||[];
g.ub(a);return a},Lua=function(a){if(g.db(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.A)(a,function(d,e){return 0==e?d:d.substring(c.length)})},Mua=function(a){g.qs("yt-remote-connected-devices",a,86400)},o6=function(){if(n6)return n6;
var a=g.rs("yt-remote-device-id");a||(a=i6(),g.qs("yt-remote-device-id",a,31536E3));for(var b=m6(),c=1,d=a;g.cb(b,d);)c++,d=a+"#"+c;return n6=d},p6=function(){var a=m6(),b=o6();
g.cb(a,b);g.ts()&&g.wb(a,b);a=Lua(a);if(g.db(a))try{g.gr("remote_sid")}catch(c){}else try{g.er("remote_sid",a.join(","),-1)}catch(c){}},Nua=function(){return g.rs("yt-remote-session-browser-channel")},Oua=function(){return g.rs("yt-remote-local-screens")||[]},Pua=function(){g.qs("yt-remote-lounge-token-expiration",!0,86400)},Qua=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.A)(Oua(),function(d){return d.loungeToken}),c=(0,g.A)(a,function(d){return d.loungeToken});
(0,g.ti)(c,function(d){return!g.cb(b,d)})&&Pua();
g.qs("yt-remote-local-screens",a,31536E3)},Rua=function(a,b){g.qs("yt-remote-session-browser-channel",a);
g.qs("yt-remote-session-screen-id",b);var c=m6(),d=o6();g.cb(c,d)||c.push(d);Mua(c);p6()},q6=function(a){a||(l6("yt-remote-session-screen-id"),l6("yt-remote-session-video-id"));
p6();a=m6();g.gb(a,o6());Mua(a)},Sua=function(){if(!r6){var a=g.qo();
a&&(r6=new g.Zn(a))}return r6?!!r6.get("yt-remote-use-staging-server"):!1},Tua=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},Uua=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},s6=function(a){a.length?Vua(a.shift(),function(){s6(a)}):t6()},Wua=function(a){return"chrome-extension://"+a+"/cast_sender.js"},Vua=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},t6=function(){var a=Uua();
a&&a(!1,"No cast extension found")},Yua=function(){if(Xua){var a=2,b=Uua(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;Vua("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",t6,c)}},Zua=function(){Yua();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);s6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},u6=function(){},$ua=function(){},bva=function(a){return(a=ava(a))?new ActiveXObject(a):new XMLHttpRequest},ava=function(a){if(!a.u&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.u=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.u},v6=function(a,b,c){g.C.call(this);
this.w=null!=c?(0,g.x)(a,c):a;this.sd=b;this.u=(0,g.x)(this.mF,this);this.o=[]},w6=function(a){a.Da=g.Vf(a.u,a.sd);
a.w.apply(null,a.o)},x6=function(a,b,c,d){this.o=a;
this.w=b;this.G=c;this.F=d||1;this.B=45E3;this.A=new g.S1(this);this.u=new g.Uf;this.u.setInterval(250)},dva=function(a,b,c){a.ej=1;
a.Ig=Z5(b.clone());a.xi=c;a.C=!0;cva(a,null)},y6=function(a,b,c,d,e){a.ej=1;
a.Ig=Z5(b.clone());a.xi=null;a.C=c;e&&(a.VB=!1);cva(a,d)},cva=function(a,b){a.Nj=(0,g.I)();
z6(a);a.xh=a.Ig.clone();$5(a.xh,"t",a.F);a.tm=0;a.Jc=a.o.Uq(a.o.im()?b:null);0<a.Hr&&(a.gp=new v6((0,g.x)(a.VC,a,a.Jc),a.Hr));a.A.ia(a.Jc,"readystatechange",a.oO);var c=a.Zh?g.hc(a.Zh):{};a.xi?(a.Pp="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Jc.send(a.xh,a.Pp,a.xi,c)):(a.Pp="GET",a.VB&&!g.je&&(c.Connection="close"),a.Jc.send(a.xh,a.Pp,null,c));a.o.Ye(1)},gva=function(a,b,c){for(var d=!0;!a.Lh&&a.tm<c.length;){var e=eva(a,c);
if(e==A6){4==b&&(a.Wg=4,B6(15),d=!1);break}else if(e==fva){a.Wg=4;B6(16);d=!1;break}else C6(a,e)}4==b&&0==c.length&&(a.Wg=1,B6(17),d=!1);a.Ze=a.Ze&&d;d||(D6(a),E6(a))},eva=function(a,b){var c=a.tm,d=b.indexOf("\n",c);
if(-1==d)return A6;c=Number(b.substring(c,d));if(isNaN(c))return fva;d+=1;if(d+c>b.length)return A6;var e=b.substr(d,c);a.tm=d+c;return e},iva=function(a,b){a.Nj=(0,g.I)();
z6(a);var c=b?window.location.hostname:"";a.xh=a.Ig.clone();Y5(a.xh,"DOMAIN",c);Y5(a.xh,"t",a.F);try{a.df=new ActiveXObject("htmlfile")}catch(n){D6(a);a.Wg=7;B6(22);E6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in F6)k=F6[l];else if(l in hva)k=F6[l]=hva[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
F6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Yc(g.uc("b/12014412"),d+"</body></html>");a.df.open();a.df.write(g.Tc(c));a.df.close();a.df.parentWindow.m=(0,g.x)(a.HN,a);a.df.parentWindow.d=(0,g.x)(a.eB,a,!0);a.df.parentWindow.rpcClose=(0,g.x)(a.eB,a,!1);c=a.df.createElement("DIV");a.df.parentWindow.document.body.appendChild(c);d=g.Fc(a.xh.toString());d=g.ed(g.Dc(d));d=g.Yc(g.uc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Zc(c,d);a.o.Ye(1)},z6=function(a){a.Vu=(0,g.I)()+a.B;
jva(a,a.B)},jva=function(a,b){if(null!=a.ak)throw Error("WatchDog timer not null");
a.ak=G6((0,g.x)(a.PN,a),b)},H6=function(a){a.ak&&(g.v.clearTimeout(a.ak),a.ak=null)},E6=function(a){a.o.Mx()||a.Lh||a.o.Wo(a)},D6=function(a){H6(a);
g.Ge(a.gp);a.gp=null;a.u.stop();g.upa(a.A);if(a.Jc){var b=a.Jc;a.Jc=null;b.abort();b.dispose()}a.df&&(a.df=null)},C6=function(a,b){try{a.o.YA(a,b),a.o.Ye(4)}catch(c){}},lva=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;kva(a,b,function(k){k?c(!0):g.v.setTimeout(function(){lva(a,b,c,d,f)},f)})}},kva=function(a,b,c){var d=new Image;
d.onload=function(){try{I6(d),c(!0)}catch(e){}};
d.onerror=function(){try{I6(d),c(!1)}catch(e){}};
d.onabort=function(){try{I6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{I6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
yua(d,a)},I6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},J6=function(){},mva=function(a){this.o=a;
this.u=new J6},nva=function(a){var b=K6(a.o,a.nk,"/mail/images/cleardot.gif");
Z5(b);lva(b.toString(),5E3,(0,g.x)(a.gE,a),3,2E3);a.Ye(1)},M6=function(a){var b=a.o.H;
if(null!=b)B6(5),b?(B6(11),L6(a.o,a,!1)):(B6(12),L6(a.o,a,!0));else if(a.Sd=new x6(a,void 0,void 0,void 0),a.Sd.Zh=a.Fr,b=a.o,b=K6(b,b.im()?a.Ok:null,a.Gr),B6(5),!g.he||g.Md(10))$5(b,"TYPE","xmlhttp"),y6(a.Sd,b,!1,a.Ok,!1);else{$5(b,"TYPE","html");var c=a.Sd;a=!!a.Ok;c.ej=3;c.Ig=Z5(b.clone());iva(c,a)}},N6=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return zua(a)},O6=function(a){g.ff.call(this);
this.headers=new g.Om;this.S=a||null;this.w=!1;this.O=this.o=null;this.da=this.H="";this.C=0;this.A="";this.B=this.Z=this.G=this.U=!1;this.F=0;this.J=null;this.ea="";this.P=this.V=!1},ova=function(a){return g.he&&g.Ld(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},pva=function(a){return"content-type"==a.toLowerCase()},rva=function(a,b){a.w=!1;
a.o&&(a.B=!0,a.o.abort(),a.B=!1);a.A=b;a.C=5;qva(a);P6(a)},qva=function(a){a.U||(a.U=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},tva=function(a){if(a.w&&"undefined"!=typeof g.X1)if(a.O[1]&&4==Q6(a)&&2==a.getStatus())R6(a,"Local request error detected and ignored");
else if(a.G&&4==Q6(a))g.Vf(a.Ox,0,a);else if(a.dispatchEvent("readystatechange"),4==Q6(a)){R6(a,"Request complete");a.w=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.od(1,String(a.H));if(!f&&g.v.self&&g.v.self.location){var k=g.v.self.location.protocol;f=k.substr(0,k.length-1)}e=!sva.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.C=6;try{var l=2<Q6(a)?a.o.statusText:""}catch(m){l=""}a.A=l+" ["+a.getStatus()+"]";qva(a)}}finally{P6(a)}}},P6=function(a,b){if(a.o){uva(a);
var c=a.o,d=a.O[0]?g.Ja:null;a.o=null;a.O=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},uva=function(a){a.o&&a.P&&(a.o.ontimeout=null);
a.J&&(g.v.clearTimeout(a.J),a.J=null)},Q6=function(a){return a.o?a.o.readyState:0},S6=function(a){try{return a.o?a.o.responseText:""}catch(b){return""}},R6=function(a,b){return b+" ["+a.da+" "+a.H+" "+a.getStatus()+"]"},T6=function(a,b,c){this.o=1;
this.u=[];this.A=[];this.B=new J6;this.G=a||null;this.H=null!=b?b:null;this.C=c||!1},vva=function(a,b){this.o=a;
this.map=b;this.context=null},wva=function(a){g.Ie.call(this,"statevent",a)},xva=function(a,b){g.Ie.call(this,"timingevent",a);
this.size=b},yva=function(a){g.Ie.call(this,"serverreachability",a)},Bva=function(a){zva(a);
if(3==a.o){var b=a.Jl++,c=a.xn.clone();Y5(c,"SID",a.w);Y5(c,"RID",b);Y5(c,"TYPE","terminate");U6(a,c);b=new x6(a,a.w,b,void 0);b.ej=2;b.Ig=Z5(c.clone());yua(new Image,b.Ig.toString());b.Nj=(0,g.I)();z6(b)}Ava(a)},Cva=function(a){a.EE(1,0);
a.xn=K6(a,null,a.Er);V6(a)},zva=function(a){a.Mg&&(a.Mg.abort(),a.Mg=null);
a.fc&&(a.fc.cancel(),a.fc=null);a.Qf&&(g.v.clearTimeout(a.Qf),a.Qf=null);W6(a);a.Ld&&(a.Ld.cancel(),a.Ld=null);a.Rg&&(g.v.clearTimeout(a.Rg),a.Rg=null)},Dva=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new vva(a.YJ++,b));2!=a.o&&3!=a.o||V6(a)},V6=function(a){a.Ld||a.Rg||(a.Rg=G6((0,g.x)(a.dB,a),0),a.Yi=0)},Fva=function(a,b){if(1==a.o){if(!b){a.Jl=Math.floor(1E5*Math.random());
var c=a.Jl++,d=new x6(a,"",c,void 0);d.Zh=null;var e=X6(a),f=a.xn.clone();Y5(f,"RID",c);Y5(f,"CVER","1");U6(a,f);dva(d,f,e);a.Ld=d;a.o=2}}else 3==a.o&&(b?Eva(a,b):0==a.u.length||a.Ld||Eva(a))},Eva=function(a,b){if(b)if(6<a.Mh){a.u=a.A.concat(a.u);
a.A.length=0;var c=a.Jl-1;var d=X6(a)}else c=b.G,d=b.xi;else c=a.Jl++,d=X6(a);var e=a.xn.clone();Y5(e,"SID",a.w);Y5(e,"RID",c);Y5(e,"AID",a.qj);U6(a,e);c=new x6(a,a.w,c,a.Yi+1);c.Zh=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Ld=c;dva(c,e,d)},U6=function(a,b){if(a.od){var c=a.od.ix();
c&&g.Rb(c,function(d,e){Y5(b,e,d)})}},X6=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.Mh&&0<b){var d=a.u[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.u[e].o,k=a.u[e].map;f=6>=a.Mh?e:f-d;try{g.Rb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.A=a.A.concat(a.u.splice(0,b));
return c.join("&")},Gva=function(a){a.fc||a.Qf||(a.F=1,a.Qf=G6((0,g.x)(a.cB,a),0),a.Ri=0)},Y6=function(a){if(a.fc||a.Qf||3<=a.Ri)return!1;
a.F++;a.Qf=G6((0,g.x)(a.cB,a),Hva(a,a.Ri));a.Ri++;return!0},L6=function(a,b,c){a.Np=c;
a.qf=b.dg;a.C||Cva(a)},W6=function(a){null!=a.Qh&&(g.v.clearTimeout(a.Qh),a.Qh=null)},Hva=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},Z6=function(a,b){if(2==b||9==b){var c=null;
a.od&&(c=null);var d=(0,g.x)(a.bP,a);c||(c=new g.Rm("//www.google.com/images/cleardot.gif"),Z5(c));kva(c.toString(),1E4,d)}else B6(2);Iva(a,b)},Iva=function(a,b){a.o=0;
a.od&&a.od.xw(b);Ava(a);zva(a)},Ava=function(a){a.o=0;
a.qf=-1;if(a.od)if(0==a.A.length&&0==a.u.length)a.od.Mq();else{g.kb(a.A);var b=g.kb(a.u);a.A.length=0;a.u.length=0;a.od.Mq(b)}},K6=function(a,b,c){var d=g.Zm(c);
if(""!=d.o)b&&g.Tm(d,b+"."+d.o),g.Um(d,d.B);else{var e=window.location;d=Cua(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Bk&&g.Rb(a.Bk,function(f,k){Y5(d,k,f)});
Y5(d,"VER",a.Mh);U6(a,d);return d},G6=function(a,b){if(!g.Oa(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},B6=function(a){$6.dispatchEvent(new wva($6,a))},Jva=function(){},a7=function(a,b,c){g.C.call(this);
this.C=null!=c?(0,g.x)(a,c):a;this.sd=b;this.B=(0,g.x)(this.lF,this);this.o=!1;this.u=0;this.w=this.Da=null;this.A=[]},Kva=function(){this.o=[];
this.u=[]},Lva=function(a,b){this.action=a;
this.params=b||{}},b7=function(a,b){g.C.call(this);
this.o=new g.J(this.yN,0,this);g.H(this,this.o);this.sd=5E3;this.u=0;if(g.Oa(a))b&&(a=(0,g.x)(a,b));else if(a&&g.Oa(a.handleEvent))a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.w=a},c7=function(a,b,c){this.J=a;
this.C=b;this.w=new g.Yn;this.u=new b7(this.DO,this);this.o=null;this.vb=!1;this.B=null;this.H="";this.G=this.A=0;this.F=[];this.P=c||!1},Mva=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.Np,sessionId:a.o.w,arrayId:a.o.qj}},Nva=function(a,b){a.G=b||0;
a.u.stop();a.o&&(3==a.o.o&&Fva(a.o),Bva(a.o));a.G=0},d7=function(a){return!!a.o&&3==a.o.o},Ova=function(a,b){(a.C.loungeIdToken=b)||a.u.stop()},e7=function(a){this.port=this.domain="";
this.o="/api/lounge";this.u=!0;a=a||document.location.href;var b=Number(g.od(4,a))||"";b&&(this.port=":"+b);this.domain=g.pd(a)||"";a=g.Pb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ob(a,"10.0")&&(this.u=!1))},f7=function(a,b){var c=a.o;
a.u&&(c="https://"+a.domain+a.port+a.o);return g.yd(c+b,{})},g7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Sa(a.A,d,!0),onError:g.Sa(a.w,e),Od:g.Sa(a.B,e)};c&&(a.zb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.yp(b,a)},Sva=function(){var a=Pva;
Qva();h7.push(a);Rva(h7)},i7=function(a,b){Qva();
var c=h7,d=Tva(a,String(b));g.db(c)?Uva(d):(Rva(c),(0,g.y)(c,function(e){e(d)}))},Qva=function(){h7||(h7=g.w("yt.mdx.remote.debug.handlers_")||[],g.Ia("yt.mdx.remote.debug.handlers_",h7,void 0))},Uva=function(a){var b=(j7+1)%50;
j7=b;k7[b]=a;l7||(l7=49==b)},Rva=function(a){var b=k7;
if(b[0]){var c=j7,d=l7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.y)(a,function(f){f(e)})}while(d!=c);
k7=Array(50);j7=-1;l7=!1}},Tva=function(a,b){var c=((0,g.I)()-Vva)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},m7=function(a){g.Q.call(this);
this.F=a;this.o=[]},Wva=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.o.push(b);return!0},Xva=function(a,b){var c=a.o.length!=b.length;
a.o=(0,g.ue)(a.o,function(f){return!!j6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=Wva(a,b[d])||c;return c},Yva=function(a,b){var c=a.o.length;
a.o=(0,g.ue)(a.o,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.o.length<c},n7=function(a,b,c,d){g.Q.call(this);
this.C=a;this.A=b;this.B=c;this.w=d;this.u=0;this.o=null;this.Da=NaN},p7=function(a){m7.call(this,"LocalScreenService");
this.w=a;this.u=NaN;o7(this);this.info("Initializing with "+h6(this.o))},Zva=function(a){if(a.o.length){var b=(0,g.A)(a.o,function(d){return d.id}),c=f7(a.w,"/pairing/get_lounge_token_batch");
g7(a.w,c,{screen_ids:b.join(",")},(0,g.x)(a.wF,a),(0,g.x)(a.vF,a))}},o7=function(a){var b=Iua(Oua());
b=(0,g.ue)(b,function(c){return!c.uuid});
return Xva(a,b)},q7=function(a,b){Qua((0,g.A)(a.o,Gua));
b&&Pua()},s7=function(a,b){g.Q.call(this);
this.C=b;var c=g.rs("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.cb(c,l)}this.o=d;this.B=a;this.w=this.A=NaN;this.u=null;r7("Initialized with "+g.Lk(this.o))},$va=function(a,b,c){var d=f7(a.B,"/pairing/get_screen_availability");
g7(a.B,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},t7=function(a,b){a:if(a6(b)!=a6(a.o))var c=!1;
else{c=g.Yb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(r7("Updated online screens: "+g.Lk(a.o)),a.o=b,a.R("screenChange"));awa(a)},u7=function(a){isNaN(a.w)||g.Lo(a.w);
a.w=g.Jo((0,g.x)(a.ju,a),0<a.A&&a.A<(0,g.I)()?2E4:1E4)},r7=function(a){i7("OnlineScreenService",a)},bwa=function(a){var b={};
(0,g.y)(a.C(),function(c){c.token?b[c.token]=c.id:this.Sb("Requesting availability of screen w/o lounge token.")});
return b},awa=function(a){a=g.Yb(g.Sb(a.o,function(b){return b}));
g.ub(a);a.length?g.qs("yt-remote-online-screen-ids",a.join(","),60):l6("yt-remote-online-screen-ids")},v7=function(a){m7.call(this,"ScreenService");
this.C=a;this.u=this.w=null;this.A=[];this.B={};cwa(this)},ewa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.de();if(k=(c?k6(k,c):null)||k6(k,b)){k.uuid=b;var l=w7(a,k);$va(a.u,l,function(m){e(m?l:null)})}else c?dwa(a,c,(0,g.x)(function(m){var n=w7(this,new e6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));$va(this.u,n,function(p){e(p?n:null)})},a),f):e(null)},fwa=function(a,b){for(var c=0,d=a.o.length;c<d;++c)if(a.o[c].name==b)return a.o[c];
return null},dwa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={zb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.yp(f7(a.C,"/pairing/get_lounge_token_batch"),e)},gwa=function(a){a.o=a.w.de();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.o.length;b<d;++b){var e=a.o[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+h6(a.o))},cwa=function(a){x7(a);
a.w=new p7(a.C);a.w.subscribe("screenChange",(0,g.x)(a.EF,a));gwa(a);a.A=Iua(g.rs("yt-remote-automatic-screen-cache")||[]);x7(a);a.info("Initializing automatic screens: "+h6(a.A));a.u=new s7(a.C,(0,g.x)(a.de,a,!0));a.u.subscribe("screenChange",(0,g.x)(function(){this.R("onlineScreenChange")},a))},w7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=k6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.qs("yt-remote-automatic-screen-cache",(0,g.A)(a.A,Gua)));x7(a);a.B[b.uuid]=b.id;g.qs("yt-remote-device-id-map",a.B,31536E3);return b},x7=function(a){a.B=g.rs("yt-remote-device-id-map")||{}},y7=function(a,b,c){g.Q.call(this);
this.O=c;this.H=a;this.u=b;this.w=null},z7=function(a,b){i7(a.O,b)},A7=function(a,b){y7.call(this,a,b,"CastSession");
this.o=null;this.A=0;this.C=(0,g.x)(this.NP,this);this.B=(0,g.x)(this.XN,this);this.A=g.Jo((0,g.x)(function(){hwa(this,null)},this),12E4)},iwa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Lk(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ja,(0,g.x)(function(){z7(this,"Failed to send message: getMdxSessionStatus.")},a)):z7(a,"Sending yt message without session: "+g.Lk(b))},hwa=function(a,b){g.Lo(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.w||a.w.id!=b){var c=(0,g.x)(a.Yo,a),d=(0,g.x)(a.je,a);a.Dx(b,c,d,5)}}else a.je(Error("Waiting for session status timed out."))},B7=function(a,b,c){y7.call(this,a,b,"DialSession");
this.A=this.G=null;this.J="";this.S=c;this.B=null;this.F=g.Ja;this.C=NaN;this.P=(0,g.x)(this.QP,this);this.o=g.Ja},jwa=function(a){a.o=a.H.bD(a.J,a.u.label,a.u.friendlyName,(0,g.x)(function(b){this.o=g.Ja;
this.Yo(b)},a),(0,g.x)(function(b){this.o=g.Ja;
this.je(b)},a))},kwa=function(a){var b={};
b.pairingCode=a.J;b.theme=a.S;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}Sua()&&(b.env_useStageMdx=1);return g.wd(b)},C7=function(a,b){y7.call(this,a,b,"ManualSession");
this.o=g.Jo((0,g.x)(this.rj,this,null),150)},D7=function(a,b,c,d){g.Q.call(this);
this.u=a;this.F=b||"233637DE";this.C=c||"cl";this.G=d||!1;this.o=null;this.B=!1;this.w=[];this.A=(0,g.x)(this.FM,this)},lwa=function(a,b){return b?g.$a(a.w,function(c){return f6(b,c.label)},a):null},E7=function(a){i7("Controller",a)},Pva=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},F7=function(a){return a.B||!!a.w.length||!!a.o},G7=function(a,b,c){b!=a.o&&(g.Ge(a.o),(a.o=b)?(c?a.R("yt-remote-cast2-receiver-resumed",b.u):a.R("yt-remote-cast2-receiver-selected",
b.u),b.subscribe("sessionScreen",(0,g.x)(a.bB,a,b)),b.w?a.R("yt-remote-cast2-session-change",b.w):c&&a.o.rj(null)):a.R("yt-remote-cast2-session-change",null))},mwa=function(a){var b=a.u.aD(),c=a.o&&a.o.u;
a=(0,g.A)(b,function(d){c&&f6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=lwa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},swa=function(a,b,c,d,e,f,k){nwa()?owa(b,e,f,k)&&(I7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?pwa(a,c):(window.__onGCastApiAvailable=function(l,m){l?pwa(a,c):(J7("Failed to load cast API: "+m),K7(!1),I7(!1),l6("yt-remote-cast-available"),l6("yt-remote-cast-receiver"),qwa(),c(!1))},d?g.Vo("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?Zua():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?t6():(Yua(),s6(rwa.map(Wua))))):H7("Cannot initialize because not running Chrome")},qwa=function(){H7("dispose");
var a=L7();a&&a.dispose();g.Ia("yt.mdx.remote.cloudview.instance_",null,void 0);twa(!1);g.Ro(M7);M7.length=0},N7=function(){return!!g.rs("yt-remote-cast-installed")},uwa=function(){var a=g.rs("yt-remote-cast-receiver");
return a?a.friendlyName:null},vwa=function(){H7("clearCurrentReceiver");
l6("yt-remote-cast-receiver")},wwa=function(){return N7()?L7()?L7().getCastSession():(J7("getCastSelector: Cast is not initialized."),null):(J7("getCastSelector: Cast API is not installed!"),null)},P7=function(){N7()?L7()?O7()?(H7("Requesting cast selector."),L7().requestSession()):(H7("Wait for cast API to be ready to request the session."),M7.push(g.Qo("yt-remote-cast2-api-ready",P7))):J7("requestCastSelector: Cast is not initialized."):J7("requestCastSelector: Cast API is not installed!")},Q7=
function(a,b){O7()?L7().setConnectedScreenStatus(a,b):J7("setConnectedScreenStatus called before ready.")},nwa=function(){var a=0<=g.Pb.search(/ (CrMo|Chrome|CriOS)\//);
return g.Iv||a},xwa=function(a,b){L7().init(a,b)},owa=function(a,b,c,d){var e=!1;
L7()||(a=new D7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.qs("yt-remote-cast-available",f);c6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){H7("onReceiverSelected: "+f.friendlyName);
g.qs("yt-remote-cast-receiver",f);c6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){H7("onReceiverResumed: "+f.friendlyName);
g.qs("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){H7("onSessionChange: "+g6(f));
f||l6("yt-remote-cast-receiver");c6("yt-remote-cast2-session-change",f)}),g.Ia("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
H7("cloudview.createSingleton_: "+e);return e},L7=function(){return g.w("yt.mdx.remote.cloudview.instance_")},pwa=function(a,b){K7(!0);
I7(!1);xwa(a,function(c){c?(twa(!0),g.So("yt-remote-cast2-api-ready")):(J7("Failed to initialize cast API."),K7(!1),l6("yt-remote-cast-available"),l6("yt-remote-cast-receiver"),qwa());b(c)})},H7=function(a){i7("cloudview",a)},J7=function(a){i7("cloudview",a)},K7=function(a){H7("setCastInstalled_ "+a);
g.qs("yt-remote-cast-installed",a)},O7=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},twa=function(a){H7("setApiReady_ "+a);
g.Ia("yt.mdx.remote.cloudview.apiReady_",a,void 0)},I7=function(a){g.Ia("yt.mdx.remote.cloudview.initializing_",a,void 0)},R7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.C=this.F=0;this.o=null;this.hasNext=this.rf=!1;this.H=this.G=this.u=this.A=0;this.w=NaN;this.B=!1;this.reset(a)},S7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.rf=!1;a.hasNext=!1;a.F=0;a.C=(0,g.I)();a.A=0;a.u=0;a.G=0;a.H=0;a.w=NaN;a.B=!1},T7=function(a){return 1==a.playerState?((0,g.I)()-a.C)/1E3:0},U7=function(a,b){a.F=b;
a.C=(0,g.I)()},V7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.I)()-a.C)/1E3+a.F;
case -1E3:return 0}return a.F},W7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&S7(a)},X7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.ic(a.o);b.hasPrevious=a.rf;b.hasNext=a.hasNext;b.playerTime=a.F;b.playerTimeAt=a.C;b.seekableStart=a.A;b.seekableEnd=a.u;b.duration=a.G;b.loadedTime=a.H;b.liveIngestionTime=a.w;return b},Z7=function(a,b){g.Q.call(this);
this.o=0;this.A=a;this.C=[];this.B=new Kva;this.w=this.u=null;this.H=(0,g.x)(this.GK,this);this.F=(0,g.x)(this.Ll,this);this.G=(0,g.x)(this.FK,this);this.J=(0,g.x)(this.RK,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Yu,this),ywa(this))):c=3;0!=c&&(b?this.Yu(c):g.Jo((0,g.x)(function(){this.Yu(c)},this),0));
var d=wwa();d&&Y7(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},$7=function(a){return new R7(a.A.getPlayerContextData())},ywa=function(a){(0,g.y)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.C.push(this.A.subscribe(b,g.Sa(this.CM,b),this))},a)},zwa=function(a){(0,g.y)(a.C,function(b){this.A.unsubscribeByKey(b)},a);
a.C.length=0},a8=function(a,b){var c=a.B;
50>c.o.length+c.u.length&&a.B.u.push(b)},c8=function(a,b,c){var d=$7(a);
U7(d,c);-1E3!=d.playerState&&(d.playerState=b);b8(a,d)},d8=function(a,b,c){a.A.sendMessage(b,c)},b8=function(a,b){zwa(a);
a.A.setPlayerContextData(X7(b));ywa(a)},Y7=function(a,b){a.w&&(a.w.removeUpdateListener(a.H),a.w.removeMediaListener(a.F),a.Ll(null));
a.w=b;a.w&&(i7("CP","Setting cast session: "+a.w.sessionId),a.w.addUpdateListener(a.H),a.w.addMediaListener(a.F),a.w.media.length&&a.Ll(a.w.media[0]))},Awa=function(a){var b=a.u.media,c=a.u.customData;
if(b&&c){var d=$7(a);b.contentId!=d.videoId&&i7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;U7(d,a.u.getEstimatedTime());b8(a,d)}else i7("CP","No cast media video. Ignoring state update.")},e8=function(a,b,c){return(0,g.x)(function(d){this.Sb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Sb("Retrying "+b+" using MDx browser channel."),d8(this,b,c))},a)},f8=function(a,b,c){g.Q.call(this);
this.B=NaN;this.P=!1;this.G=this.F=this.H=this.J=NaN;this.O=[];this.A=this.C=this.w=this.Ta=this.o=null;this.U=a;this.O.push(g.Hq(window,"beforeunload",(0,g.x)(this.oF,this)));this.u=[];this.Ta=new R7;this.S=b.id;this.o=Bwa(this,c);this.o.subscribe("handlerOpened",this.KK,this);this.o.subscribe("handlerClosed",this.HK,this);this.o.subscribe("handlerError",this.IK,this);this.o.subscribe("handlerMessage",this.JK,this);Ova(this.o,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Ta.videoId;
g.ts()&&g.qs("yt-remote-session-video-id",d)},this)},g8=function(a){i7("conn",a)},Bwa=function(a,b){return new c7(f7(a.U,"/bc"),b)},h8=function(a,b){a.R("proxyStateChange",b)},Cwa=function(a){a.B=g.Jo((0,g.x)(function(){g8("Connecting timeout");
this.Wi(1)},a),2E4)},i8=function(a){g.Lo(a.B);
a.B=NaN},j8=function(a){g.Lo(a.J);
a.J=NaN},Dwa=function(a){k8(a);
a.H=g.Jo((0,g.x)(function(){l8(this,"getNowPlaying")},a),2E4)},k8=function(a){g.Lo(a.H);
a.H=NaN},Fwa=function(a,b){b&&(i8(a),j8(a));
b==(d7(a.o)&&isNaN(a.B))?b&&(h8(a,1),l8(a,"getSubtitlesTrack")):b?(a.Bx()&&a.Ta.reset(),h8(a,1),l8(a,"getNowPlaying"),Ewa(a)):a.Wi(1)},Gwa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Ta.videoId&&(g.ec(b.params)?a.Ta.o=null:a.Ta.o=b.params,a.R("remotePlayerChange"))},Hwa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Ta.listId=b.params.listId||a.Ta.listId;W7(a.Ta,c,d);a.R("remoteQueueChange")},Jwa=function(a,b){b.params=b.params||{};
Hwa(a,b);Iwa(a,b);a.R("autoplayDismissed")},Iwa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
U7(a.Ta,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Ta.playerState&&(c=-1E3);a.Ta.playerState=c;c=Number(b.params.loadedTime);a.Ta.H=isNaN(c)?0:c;c=Number(b.params.duration);a.Ta.G=isNaN(c)?0:c;c=a.Ta;var d=Number(b.params.liveIngestionTime);c.w=d;c.B=isNaN(d)?!1:!0;c=a.Ta;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.A=isNaN(d)?0:d;c.u=isNaN(e)?0:e;1==a.Ta.playerState?Dwa(a):k8(a);a.R("remotePlayerChange")},Kwa=function(a,b){if(-1E3!=
a.Ta.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Ta.playerState=c;c=parseInt(b.params.currentTime,10);U7(a.Ta,isNaN(c)?0:c);a.R("remotePlayerChange")}},Lwa=function(a,b){var c="true"==b.params.muted;
a.Ta.volume=parseInt(b.params.volume,10);a.Ta.muted=c;a.R("remotePlayerChange")},Mwa=function(a,b){a.C=b.params.videoId;
a.R("nowAutoplaying",parseInt(b.params.timeout,10))},Nwa=function(a,b){var c="true"==b.params.hasNext;
a.Ta.rf="true"==b.params.hasPrevious;a.Ta.hasNext=c;a.R("previousNextChange")},Ewa=function(a){g.Lo(a.G);
a.G=g.Jo((0,g.x)(a.Wi,a,1),864E5)},l8=function(a,b,c){c?g8("Sending: action="+b+", params="+g.Lk(c)):g8("Sending: action="+b);
a.o.sendMessage(b,c)},m8=function(a){m7.call(this,"ScreenServiceProxy");
this.rd=a;this.u=[];this.u.push(this.rd.$_s("screenChange",(0,g.x)(this.LP,this)));this.u.push(this.rd.$_s("onlineScreenChange",(0,g.x)(this.hM,this)))},Swa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.M("MDX_CONFIG")||b;Kua();p6();n8||(n8=new e7(b?b.loungeApiHost:void 0),Sua()&&(n8.o="/api/loungedev"));o8||(o8=g.w("yt.mdx.remote.deferredProxies_")||[],g.Ia("yt.mdx.remote.deferredProxies_",o8,void 0));Owa();var c=p8();if(!c){var d=new v7(n8);g.Ia("yt.mdx.remote.screenService_",d,void 0);c=p8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);swa(a,d,function(m){m?q8()&&Q7(q8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){c6("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.w("yt.mdx.remote.initialized_")&&(g.Ia("yt.mdx.remote.initialized_",!0,void 0),r8("Initializing: "+g.Lk(b)),s8.push(g.Qo("yt-remote-cast2-availability-change",function(){c6("yt-remote-receiver-availability-change")})),s8.push(g.Qo("yt-remote-cast2-receiver-selected",function(){t8(null);
c6("yt-remote-auto-connect","cast-selector-receiver")})),s8.push(g.Qo("yt-remote-cast2-receiver-resumed",function(){c6("yt-remote-receiver-resumed","cast-selector-receiver")})),s8.push(g.Qo("yt-remote-cast2-session-change",Pwa)),s8.push(g.Qo("yt-remote-connection-change",function(m){m?Q7(q8(),"YouTube TV"):u8()||(Q7(null,null),vwa())})),a=v8(),b.isAuto&&(a.id+="#dial"),g.Zo("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),r8(" -- with channel params: "+
g.Lk(a)),Qwa(a),c.start(),q8()||Rwa())},Uwa=function(){var a=Twa();
N7()&&g.rs("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},Twa=function(){var a=p8().rd.$_gos();
var b=w8();b&&x8()&&(j6(a,b)||a.push(b));return Jua(a)},y8=function(){var a=Vwa();
!a&&N7()&&uwa()&&(a={key:"cast-selector-receiver",name:uwa()});return a},Vwa=function(){var a=Twa(),b=w8();
b||(b=u8());return g.$a(a,function(c){return b&&f6(b,c.key)?!0:!1})},w8=function(){var a=q8();
if(!a)return null;var b=p8().de();return k6(b,a)},Pwa=function(a){r8("remote.onCastSessionChange_: "+g6(a));
if(a){var b=w8();b&&b.id==a.id?Q7(b.id,"YouTube TV"):(b&&z8(),A8(a,1))}else x8()&&z8()},z8=function(){O7()?L7().stopSession():J7("stopSession called before API ready.");
var a=x8();a&&(a.disconnect(1),B8(null))},C8=function(){var a=x8();
return!!a&&3!=a.getProxyState()},r8=function(a){i7("remote",a)},p8=function(){if(!D8){var a=g.w("yt.mdx.remote.screenService_");
D8=a?new m8(a):null}return D8},q8=function(){return g.w("yt.mdx.remote.currentScreenId_")},Wwa=function(a){g.Ia("yt.mdx.remote.currentScreenId_",a,void 0)},Xwa=function(){return g.w("yt.mdx.remote.connectData_")},t8=function(a){g.Ia("yt.mdx.remote.connectData_",a,void 0)},x8=function(){return g.w("yt.mdx.remote.connection_")},B8=function(a){var b=x8();
t8(null);a||Wwa("");g.Ia("yt.mdx.remote.connection_",a,void 0);o8&&((0,g.y)(o8,function(c){c(a)}),o8.length=0);
b&&!a?c6("yt-remote-connection-change",!1):!b&&a&&c6("yt-remote-connection-change",!0)},u8=function(){var a=g.ts();
if(!a)return null;var b=p8().de();return k6(b,a)},A8=function(a,b){q8();
w8()&&w8();if(E8)F8=a;else{Wwa(a.id);var c=new f8(n8,a,v8());c.connect(b,Xwa());c.subscribe("beforeDisconnect",function(d){c6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){x8()&&(x8(),B8(null))});
B8(c)}},Rwa=function(){var a=u8();
a?(r8("Resume connection to: "+g6(a)),A8(a,0)):(q6(),vwa(),r8("Skipping connecting because no session screen found."))},Owa=function(){var a=v8();
if(g.ec(a)){a=o6();var b=g.rs("yt-remote-session-name")||"",c=g.rs("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ia("yt.mdx.remote.channelParams_",a,void 0)}},v8=function(){return g.w("yt.mdx.remote.channelParams_")||{}},Qwa=function(a){a?(g.qs("yt-remote-session-app",a.app),g.qs("yt-remote-session-name",a.name)):(l6("yt-remote-session-app"),l6("yt-remote-session-name"));
g.Ia("yt.mdx.remote.channelParams_",a,void 0)},G8=function(a,b,c){g.C.call(this);
this.B=a;this.u=b;this.w=new g.P(this);g.H(this,this.w);this.w.L(b,"onCaptionsTrackListChanged",this.DL);this.w.L(b,"captionschanged",this.EK);this.w.L(b,"captionssettingschanged",this.pC);this.w.L(b,"videoplayerreset",this.Zo);this.w.L(b,"mdxautoplaycancel",this.fE);this.S=this.w.L(b,"onVolumeChange",this.IA);this.G=!1;this.o=c;c.subscribe("proxyStateChange",this.XA,this);c.subscribe("remotePlayerChange",this.Pl,this);c.subscribe("remoteQueueChange",this.Zo,this);c.subscribe("autoplayUpNext",this.yA,
this);c.subscribe("previousNextChange",this.UA,this);c.subscribe("nowAutoplaying",this.QA,this);c.subscribe("autoplayDismissed",this.xA,this);this.suggestion=null;this.H=new g.rD(64);this.A=new g.J(this.nC,500,this);g.H(this,this.A);this.C=new g.J(this.oC,1E3,this);g.H(this,this.C);this.P=new a7(this.mP,0,this);g.H(this,this.P);this.F={};this.O=new g.J(this.NC,1E3,this);g.H(this,this.O);this.J=new v6(this.gI,1E3,this);g.H(this,this.J);this.U=g.Ja;this.pC();this.Zo();this.Pl()},H8=function(a,b){var c=
a.B,d=a.u.getVideoData().lengthSeconds;
c.O=b||0;c.player.R("progresssync",b,d)},Ywa=function(a){H8(a,0);
a.A.stop();I8(a,new g.rD(64))},K8=function(a,b){if(J8(a)&&!a.G){var c=null;
b&&(c={style:a.u.getSubtitlesUserSettings()},g.kc(c,b));a.o.bC(a.u.getVideoData(1).videoId,c);a.F=$7(a.o).o}},L8=function(a,b){var c=a.u.getPlaylist();
if(c){var d=c.Za;var e=c.listId.toString()}c=a.u.getVideoData(1);a.o.playVideo(c.videoId,b,d,e,c.playerParams,c.tf,g.AB(c));I8(a,new g.rD(1))},Zwa=function(a,b){if(b){var c=a.u.getOption("captions","tracklist",{FT:1});
c&&c.length?(a.u.setOption("captions","track",b),a.G=!1):(a.u.loadModule("captions"),a.G=!0)}else a.u.setOption("captions","track",{})},J8=function(a){return $7(a.o).videoId==a.u.getVideoData(1).videoId},I8=function(a,b){a.C.stop();
var c=a.H;if(!g.xD(c,b)){var d=g.W(b,2);d!=g.W(a.H,2)&&g.tT(a.u.app,d);a.H=b;$wa(a.B,c,b)}},M8=function(){g.V.call(this,{D:"div",
I:"ytp-mdx-popup-dialog",M:{role:"dialog"},K:[{D:"div",I:"ytp-mdx-popup-dialog-inner-content",K:[{D:"div",I:"ytp-mdx-popup-title",W:"Anda telah logout"},{D:"div",I:"ytp-mdx-popup-description",W:"Video yang Anda tonton dapat ditambahkan ke histori tontonan TV, dan akan memengaruhi rekomendasi konten di TV. Untuk mencegahnya, batalkan dan login ke YouTube di komputer Anda"},{D:"div",I:"ytp-mdx-privacy-popup-buttons",K:[{D:"button",X:["ytp-button","ytp-mdx-privacy-popup-cancel"],W:"Batalkan"},{D:"button",
X:["ytp-button","ytp-mdx-privacy-popup-confirm"],W:"Konfirmasi"}]}]}]});this.u=new g.jM(this,250);g.H(this,this.u);this.C=this.o["ytp-mdx-privacy-popup-cancel"];this.L(this.C,"click",this.w);this.A=this.o["ytp-mdx-privacy-popup-confirm"];this.L(this.A,"click",this.B)},N8=function(a){g.V.call(this,{D:"div",
I:"ytp-remote",K:[{D:"div",I:"ytp-remote-display-status",K:[{D:"div",I:"ytp-remote-display-status-icon",K:[g.lM()]},{D:"div",I:"ytp-remote-display-status-text",W:"{{statustext}}"}]}]});this.u=new g.jM(this,250);g.H(this,this.u);this.w=a;this.L(a,"presentingplayerstatechange",this.A);axa(this,g.yL(a))},axa=function(a,b){if(3==a.w.getPresentingPlayerType()){var c={RECEIVER_NAME:a.w.getOption("remote","currentReceiver").name};
c=g.W(b,128)?g.PM("Terjadi error pada $RECEIVER_NAME",c):g.yD(b)||g.W(b,4)?g.PM("Diputar di $RECEIVER_NAME",c):g.PM("Terhubung ke $RECEIVER_NAME",c);a.ha("statustext",c);a.u.show()}else a.u.hide()},O8=function(a,b){g.HO.call(this,"Diputar di",0,a,b);
this.u=a;this.C={};this.L(a,"onMdxReceiversChange",this.J);this.L(a,"presentingplayerstatechange",this.J);this.J()},P8=function(a){g.RP.call(this,a);
this.u={key:i6(),name:"Komputer ini"};this.B=null;this.A=[];this.S=this.o=null;this.J=[this.u];this.w=this.u;this.F=new g.rD(64);this.O=0;this.H=-1;this.C=null;if(!g.Kx(this.player.N())){a=this.player;var b=g.YC(a);b&&(b=b.Bl())&&(b=new O8(a,b),g.H(this,b));b=new N8(a);g.H(this,b);g.QL(a,b.element,4);this.C=new M8;g.H(this,this.C);g.QL(a,this.C.element,4);this.P=!!u8()}this.G=null},Q8=function(a){a.G&&(a.player.removeEventListener("presentingplayerstatechange",a.G),a.G=null)},$wa=function(a,b,c){a.F=
c;
a.player.R("presentingplayerstatechange",new g.DD(c,b))},R8=function(a,b){if(b.key!=a.w.key)if(b.key==a.u.key)z8();
else{var c;(c=!g.R(a.player.N().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.M("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.M("SESSION_INDEX")&&!g.M("LOGGED_IN")))||a.P||!a.C);if(c?0:g.Tx(a.player.N())||g.Xx(a.player.N()))g.yD(g.yL(a.player))?a.player.pauseVideo():(a.G=(0,g.x)(a.cO,a),a.player.addEventListener("presentingplayerstatechange",a.G)),a.C&&a.C.u.show(),x8()||(E8=!0);a.w=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2==
a.player.app.U||1==a.player.app.U)&&g.R(a.player.N().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.wa(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.tf,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(c=g.AB(c))&&(d.locationInfo=c);c=d}r8("Connecting to: "+g.Lk(b));"cast-selector-receiver"==
b.key?(t8(c||null),c=c||null,O7()?L7().setLaunchParams(c):J7("setLaunchParams called before ready.")):!c&&C8()&&q8()==b.key?c6("yt-remote-connection-change",!0):(z8(),t8(c||null),c=p8().de(),(c=k6(c,b.key))&&A8(c,1))}},hva={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},F6={"'":"\\'"},bxa={},Fua={oQ:"atp",SS:"ska",HS:"que",bS:"mus",RS:"sus",nR:"dsp",OS:"seq"};
d6.prototype.Ng=function(){var a=new d6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.w=this.w;a.u=this.u;a.o=this.o};
var r6,n6="",Xua=Tua("loadCastFramework")||Tua("loadCastApplicationFramework"),rwa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];u6.prototype.o=null;u6.prototype.getOptions=function(){var a;(a=this.o)||(a={},ava(this)&&(a[0]=!0,a[1]=!0),a=this.o=a);return a};var S8;g.Ua($ua,u6);S8=new $ua;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Ua(v6,g.C);g.h=v6.prototype;g.h.dj=!1;g.h.Nk=0;g.h.Da=null;g.h.Lx=function(a){this.o=arguments;this.Da||this.Nk?this.dj=!0:w6(this)};
g.h.stop=function(){this.Da&&(g.v.clearTimeout(this.Da),this.Da=null,this.dj=!1,this.o=[])};
g.h.pause=function(){this.Nk++};
g.h.resume=function(){this.Nk--;this.Nk||!this.dj||this.Da||(this.dj=!1,w6(this))};
g.h.Y=function(){v6.Gb.Y.call(this);this.stop()};
g.h.mF=function(){this.Da=null;this.dj&&!this.Nk&&(this.dj=!1,w6(this))};g.h=x6.prototype;g.h.Zh=null;g.h.Ze=!1;g.h.ak=null;g.h.Vu=null;g.h.Nj=null;g.h.ej=null;g.h.Ig=null;g.h.xh=null;g.h.xi=null;g.h.Jc=null;g.h.tm=0;g.h.df=null;g.h.Pp=null;g.h.Wg=null;g.h.Pk=-1;g.h.VB=!0;g.h.Lh=!1;g.h.Hr=0;g.h.gp=null;var fva={},A6={};g.h=x6.prototype;g.h.setTimeout=function(a){this.B=a};
g.h.oO=function(a){a=a.target;var b=this.gp;b&&3==Q6(a)?b.Lx():this.VC(a)};
g.h.VC=function(a){try{if(a==this.Jc)a:{var b=Q6(this.Jc),c=this.Jc.C,d=this.Jc.getStatus();if(g.he&&!g.Md(10)||g.je&&!g.Ld("420+")){if(4>b)break a}else if(3>b||3==b&&!g.xh&&!S6(this.Jc))break a;this.Lh||4!=b||7==c||(8==c||0>=d?this.o.Ye(3):this.o.Ye(2));H6(this);var e=this.Jc.getStatus();this.Pk=e;var f=S6(this.Jc);(this.Ze=200==e)?(4==b&&D6(this),this.C?(gva(this,b,f),g.xh&&this.Ze&&3==b&&(this.A.ia(this.u,"tick",this.iO),this.u.start())):C6(this,f),this.Ze&&!this.Lh&&(4==b?this.o.Wo(this):(this.Ze=
!1,z6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Wg=3,B6(13)):(this.Wg=0,B6(14)),D6(this),E6(this))}}catch(k){this.Jc&&S6(this.Jc)}finally{}};
g.h.iO=function(){var a=Q6(this.Jc),b=S6(this.Jc);this.tm<b.length&&(H6(this),gva(this,a,b),this.Ze&&4!=a&&z6(this))};
g.h.HN=function(a){G6((0,g.x)(this.GN,this,a),0)};
g.h.GN=function(a){this.Lh||(H6(this),C6(this,a),z6(this))};
g.h.eB=function(a){G6((0,g.x)(this.FN,this,a),0)};
g.h.FN=function(a){this.Lh||(D6(this),this.Ze=a,this.o.Wo(this),this.o.Ye(4))};
g.h.cancel=function(){this.Lh=!0;D6(this)};
g.h.PN=function(){this.ak=null;var a=(0,g.I)();0<=a-this.Vu?(2!=this.ej&&this.o.Ye(3),D6(this),this.Wg=2,B6(18),E6(this)):jva(this,this.Vu-a)};
g.h.getLastError=function(){return this.Wg};J6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
J6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};g.h=mva.prototype;g.h.Fr=null;g.h.Sd=null;g.h.hp=!1;g.h.Nx=null;g.h.tn=null;g.h.ws=null;g.h.Gr=null;g.h.Be=null;g.h.dg=-1;g.h.Ok=null;g.h.nk=null;g.h.connect=function(a){this.Gr=a;a=K6(this.o,null,this.Gr);B6(3);this.Nx=(0,g.I)();var b=this.o.G;null!=b?(this.Ok=b[0],(this.nk=b[1])?(this.Be=1,nva(this)):(this.Be=2,M6(this))):($5(a,"MODE","init"),this.Sd=new x6(this,void 0,void 0,void 0),this.Sd.Zh=this.Fr,y6(this.Sd,a,!1,null,!0),this.Be=0)};
g.h.gE=function(a){if(a)this.Be=2,M6(this);else{B6(4);var b=this.o;b.qf=b.Mg.dg;Z6(b,9)}a&&this.Ye(2)};
g.h.Uq=function(a){return this.o.Uq(a)};
g.h.abort=function(){this.Sd&&(this.Sd.cancel(),this.Sd=null);this.dg=-1};
g.h.Mx=function(){return!1};
g.h.YA=function(a,b){this.dg=a.Pk;if(0==this.Be)if(b){try{var c=this.u.parse(b)}catch(d){c=this.o;c.qf=this.dg;Z6(c,2);return}this.Ok=c[0];this.nk=c[1]}else c=this.o,c.qf=this.dg,Z6(c,2);else if(2==this.Be)if(this.hp)B6(7),this.ws=(0,g.I)();else if("11111"==b){if(B6(6),this.hp=!0,this.tn=(0,g.I)(),c=this.tn-this.Nx,!g.he||g.Md(10)||500>c)this.dg=200,this.Sd.cancel(),B6(12),L6(this.o,this,!0)}else B6(8),this.tn=this.ws=(0,g.I)(),this.hp=!1};
g.h.Wo=function(){this.dg=this.Sd.Pk;if(this.Sd.Ze)0==this.Be?this.nk?(this.Be=1,nva(this)):(this.Be=2,M6(this)):2==this.Be&&((!g.he||g.Md(10)?!this.hp:200>this.ws-this.tn)?(B6(11),L6(this.o,this,!1)):(B6(12),L6(this.o,this,!0)));else{0==this.Be?B6(9):2==this.Be&&B6(10);var a=this.o;this.Sd.getLastError();a.qf=this.dg;Z6(a,2)}};
g.h.im=function(){return this.o.im()};
g.h.isActive=function(){return this.o.isActive()};
g.h.Ye=function(a){this.o.Ye(a)};g.Ua(O6,g.ff);var sva=/^https?$/i,cxa=["POST","PUT"];g.h=O6.prototype;
g.h.send=function(a,b,c,d){if(this.o)throw Error("[goog.net.XhrIo] Object is active with another request="+this.H+"; newUri="+a);b=b?b.toUpperCase():"GET";this.H=a;this.A="";this.C=0;this.da=b;this.U=!1;this.w=!0;this.o=this.S?bva(this.S):bva(S8);this.O=this.S?this.S.getOptions():S8.getOptions();this.o.onreadystatechange=(0,g.x)(this.Ox,this);try{b6(R6(this,"Opening Xhr")),this.Z=!0,this.o.open(b,String(a),!0),this.Z=!1}catch(f){b6(R6(this,"Error opening Xhr: "+f.message));rva(this,f);return}a=c||
"";var e=this.headers.clone();d&&Bua(d,function(f,k){e.set(k,f)});
d=g.$a(e.ye(),pva);c=g.v.FormData&&a instanceof g.v.FormData;!g.cb(cxa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.o.setRequestHeader(k,f)},this);
this.ea&&(this.o.responseType=this.ea);"withCredentials"in this.o&&this.o.withCredentials!==this.V&&(this.o.withCredentials=this.V);try{uva(this),0<this.F&&(this.P=ova(this.o),b6(R6(this,"Will abort after "+this.F+"ms if incomplete, xhr2 "+this.P)),this.P?(this.o.timeout=this.F,this.o.ontimeout=(0,g.x)(this.Px,this)):this.J=g.Vf(this.Px,this.F,this)),b6(R6(this,"Sending request")),this.G=!0,this.o.send(a),this.G=!1}catch(f){b6(R6(this,"Send error: "+f.message)),rva(this,f)}};
g.h.Px=function(){"undefined"!=typeof g.X1&&this.o&&(this.A="Timed out after "+this.F+"ms, aborting",this.C=8,R6(this,this.A),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.o&&this.w&&(R6(this,"Aborting"),this.w=!1,this.B=!0,this.o.abort(),this.B=!1,this.C=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),P6(this))};
g.h.Y=function(){this.o&&(this.w&&(this.w=!1,this.B=!0,this.o.abort(),this.B=!1),P6(this,!0));O6.Gb.Y.call(this)};
g.h.Ox=function(){this.la()||(this.Z||this.G||this.B?tva(this):this.EM())};
g.h.EM=function(){tva(this)};
g.h.isActive=function(){return!!this.o};
g.h.getStatus=function(){try{return 2<Q6(this)?this.o.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return"string"===typeof this.A?this.A:String(this.A)};g.h=T6.prototype;g.h.Bk=null;g.h.Ld=null;g.h.fc=null;g.h.Er=null;g.h.xn=null;g.h.jw=null;g.h.Ln=null;g.h.Jl=0;g.h.YJ=0;g.h.od=null;g.h.Rg=null;g.h.Qf=null;g.h.Qh=null;g.h.Mg=null;g.h.Np=null;g.h.qj=-1;g.h.Ay=-1;g.h.qf=-1;g.h.Yi=0;g.h.Ri=0;g.h.Mh=8;var $6=new g.ff;g.Ua(wva,g.Ie);g.Ua(xva,g.Ie);g.Ua(yva,g.Ie);g.h=T6.prototype;g.h.connect=function(a,b,c,d,e){B6(0);this.Er=b;this.Bk=c||{};d&&void 0!==e&&(this.Bk.OSID=d,this.Bk.OAID=e);this.C?(G6((0,g.x)(this.Ew,this,a),100),Cva(this)):this.Ew(a)};
g.h.Ew=function(a){this.Mg=new mva(this);this.Mg.Fr=null;this.Mg.u=this.B;this.Mg.connect(a)};
g.h.Mx=function(){return 0==this.o};
g.h.dB=function(a){this.Rg=null;Fva(this,a)};
g.h.cB=function(){this.Qf=null;this.fc=new x6(this,this.w,"rpc",this.F);this.fc.Zh=null;this.fc.Hr=0;var a=this.jw.clone();Y5(a,"RID","rpc");Y5(a,"SID",this.w);Y5(a,"CI",this.Np?"0":"1");Y5(a,"AID",this.qj);U6(this,a);if(!g.he||g.Md(10))Y5(a,"TYPE","xmlhttp"),y6(this.fc,a,!0,this.Ln,!1);else{Y5(a,"TYPE","html");var b=this.fc,c=!!this.Ln;b.ej=3;b.Ig=Z5(a.clone());iva(b,c)}};
g.h.YA=function(a,b){if(0!=this.o&&(this.fc==a||this.Ld==a))if(this.qf=a.Pk,this.Ld==a&&3==this.o)if(7<this.Mh){try{var c=this.B.parse(b)}catch(f){c=null}if(Array.isArray(c)&&3==c.length)if(0==c[0])a:{if(!this.Qf){if(this.fc)if(this.fc.Nj+3E3<this.Ld.Nj)W6(this),this.fc.cancel(),this.fc=null;else break a;Y6(this);B6(19)}}else this.Ay=c[1],0<this.Ay-this.qj&&37500>c[2]&&this.Np&&0==this.Ri&&!this.Qh&&(this.Qh=G6((0,g.x)(this.AK,this),6E3));else Z6(this,11)}else b!=bxa.LQ.o&&Z6(this,11);else if(this.fc==
a&&W6(this),!g.Db(b)){c=this.B.parse(b);for(var d=0;d<c.length;d++){var e=c[d];this.qj=e[0];e=e[1];2==this.o?"c"==e[0]?(this.w=e[1],this.Ln=e[2],e=e[3],null!=e?this.Mh=e:this.Mh=6,this.o=3,this.od&&this.od.zw(),this.jw=K6(this,this.im()?this.Ln:null,this.Er),Gva(this)):"stop"==e[0]&&Z6(this,7):3==this.o&&("stop"==e[0]?Z6(this,7):"noop"!=e[0]&&this.od&&this.od.yw(e),this.Ri=0)}}};
g.h.AK=function(){null!=this.Qh&&(this.Qh=null,this.fc.cancel(),this.fc=null,Y6(this),B6(20))};
g.h.Wo=function(a){if(this.fc==a){W6(this);this.fc=null;var b=2}else if(this.Ld==a)this.Ld=null,b=1;else return;this.qf=a.Pk;if(0!=this.o)if(a.Ze)1==b?(b=(0,g.I)()-a.Nj,$6.dispatchEvent(new xva($6,a.xi?a.xi.length:0,b,this.Yi)),V6(this),this.A.length=0):Gva(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.qf)){if(d=1==b)this.Ld||this.Rg||1==this.o||2<=this.Yi?d=!1:(this.Rg=G6((0,g.x)(this.dB,this,a),Hva(this,this.Yi)),this.Yi++,d=!0);d=!(d||2==b&&Y6(this))}if(d)switch(c){case 1:Z6(this,
5);break;case 4:Z6(this,10);break;case 3:Z6(this,6);break;case 7:Z6(this,12);break;default:Z6(this,2)}}};
g.h.EE=function(a){if(!g.cb(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.bP=function(a){a?B6(2):(B6(1),Iva(this,8))};
g.h.Uq=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new O6;a.V=!1;return a};
g.h.isActive=function(){return!!this.od&&this.od.isActive(this)};
g.h.Ye=function(a){$6.dispatchEvent(new yva($6,a))};
g.h.im=function(){return!(!g.he||g.Md(10))};
g.h=Jva.prototype;g.h.zw=function(){};
g.h.yw=function(){};
g.h.xw=function(){};
g.h.Mq=function(){};
g.h.ix=function(){return{}};
g.h.isActive=function(){return!0};g.Ua(a7,g.C);g.h=a7.prototype;g.h.kF=function(a){this.A=arguments;this.o=!1;this.Da?this.w=(0,g.I)()+this.sd:this.Da=g.Vf(this.B,this.sd)};
g.h.stop=function(){this.Da&&(g.v.clearTimeout(this.Da),this.Da=null);this.w=null;this.o=!1;this.A=[]};
g.h.pause=function(){++this.u};
g.h.resume=function(){this.u&&(--this.u,!this.u&&this.o&&(this.o=!1,this.C.apply(null,this.A)))};
g.h.Y=function(){this.stop();a7.Gb.Y.call(this)};
g.h.lF=function(){this.w?(this.Da=g.Vf(this.B,this.w-(0,g.I)()),this.w=null):(this.Da=null,this.u?this.o=!0:(this.o=!1,this.C.apply(null,this.A)))};g.h=Kva.prototype;g.h.isEmpty=function(){return g.db(this.o)&&g.db(this.u)};
g.h.clear=function(){this.o=[];this.u=[]};
g.h.contains=function(a){return g.cb(this.o,a)||g.cb(this.u,a)};
g.h.remove=function(a){var b=this.o;var c=(0,g.zpa)(b,a);0<=c?(g.fb(b,c),b=!0):b=!1;return b||g.gb(this.u,a)};
g.h.Dd=function(){for(var a=[],b=this.o.length-1;0<=b;--b)a.push(this.o[b]);var c=this.u.length;for(b=0;b<c;++b)a.push(this.u[b]);return a};g.Ua(b7,g.C);g.h=b7.prototype;g.h.yN=function(){this.sd=Math.min(3E5,2*this.sd);this.w();this.u&&this.start()};
g.h.start=function(){var a=this.sd+15E3*Math.random();g.An(this.o,a);this.u=(0,g.I)()+a};
g.h.stop=function(){this.o.stop();this.u=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.sd=5E3};g.Ua(c7,Jva);g.h=c7.prototype;g.h.subscribe=function(a,b,c){return this.w.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.w.unsubscribe(a,b,c)};
g.h.ug=function(a){return this.w.ai(a)};
g.h.R=function(a,b){return this.w.R.apply(this.w,arguments)};
g.h.dispose=function(){this.vb||(this.vb=!0,g.Ge(this.w),Nva(this),g.Ge(this.u),this.u=null)};
g.h.la=function(){return this.vb};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.H="";this.u.stop();this.B=a||null;this.A=b||0;a=this.J+"/test";b=this.J+"/bind";var d=new T6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.P),e=this.o;e&&(e.od=null);d.od=this;this.o=d;e?this.o.connect(a,b,this.C,e.w,e.qj):c?this.o.connect(a,b,this.C,c.sessionId,c.arrayId):this.o.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.kc(c,b);this.u.isActive()||2==(this.o?this.o.o:0)?this.F.push(c):d7(this)&&Dva(this.o,c)};
g.h.zw=function(){this.u.reset();this.B=null;this.A=0;if(this.F.length){var a=this.F;this.F=[];for(var b=0,c=a.length;b<c;++b)Dva(this.o,a[b])}this.R("handlerOpened")};
g.h.xw=function(a){var b=2==a&&401==this.o.qf;4==a||b||this.u.start();this.R("handlerError",a)};
g.h.Mq=function(a){if(!this.u.isActive())this.R("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.F.push(d)}};
g.h.ix=function(){var a={v:2};this.H&&(a.gsessionid=this.H);0!=this.A&&(a.ui=""+this.A);0!=this.G&&(a.ui=""+this.G);this.B&&g.kc(a,this.B);return a};
g.h.yw=function(a){"S"==a[0]?this.H=a[1]:"gracefulReconnect"==a[0]?(this.u.start(),Bva(this.o)):this.R("handlerMessage",new Lva(a[0],a[1]))};
g.h.DO=function(){this.u.isActive();var a=this.o,b=0;a.fc&&b++;a.Ld&&b++;0==b&&this.connect(this.B,this.A)};e7.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
e7.prototype.w=function(a,b){a(Error("Request error: "+b.status))};
e7.prototype.B=function(a){a(Error("request timed out"))};var Vva=(0,g.I)(),h7=null,k7=Array(50),j7=-1,l7=!1;g.Ua(m7,g.Q);m7.prototype.de=function(){return this.o};
m7.prototype.contains=function(a){return!!j6(this.o,a)};
m7.prototype.get=function(a){return a?k6(this.o,a):null};
m7.prototype.info=function(a){i7(this.F,a)};g.r(n7,g.Q);g.h=n7.prototype;g.h.start=function(){!this.o&&isNaN(this.Da)&&this.ZC()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);isNaN(this.Da)||(g.Lo(this.Da),this.Da=NaN)};
g.h.Y=function(){this.stop();g.Q.prototype.Y.call(this)};
g.h.ZC=function(){this.Da=NaN;this.o=g.yp(f7(this.C,"/pairing/get_screen"),{method:"POST",zb:{pairing_code:this.A},timeout:5E3,onSuccess:(0,g.x)(this.JP,this),onError:(0,g.x)(this.IP,this),Od:(0,g.x)(this.KP,this)})};
g.h.JP=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.B;c.name=this.w;this.R("pairingComplete",new e6(c))};
g.h.IP=function(a){this.o=null;a.status&&404==a.status?this.u>=dxa.length?this.R("pairingFailed",Error("DIAL polling timed out")):(a=dxa[this.u],this.Da=g.Jo((0,g.x)(this.ZC,this),a),this.u++):this.R("pairingFailed",Error("Server error "+a.status))};
g.h.KP=function(){this.o=null;this.R("pairingFailed",Error("Server not responding"))};
var dxa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Ua(p7,m7);g.h=p7.prototype;g.h.start=function(){o7(this)&&this.R("screenChange");!g.rs("yt-remote-lounge-token-expiration")&&Zva(this);g.Lo(this.u);this.u=g.Jo((0,g.x)(this.start,this),1E4)};
g.h.add=function(a,b){o7(this);Wva(this,a);q7(this,!1);this.R("screenChange");b(a);a.token||Zva(this)};
g.h.remove=function(a,b){var c=o7(this);Yva(this,a)&&(q7(this,!1),c=!0);b(a);c&&this.R("screenChange")};
g.h.Kp=function(a,b,c,d){var e=o7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,q7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.R("screenChange")};
g.h.Y=function(){g.Lo(this.u);p7.Gb.Y.call(this)};
g.h.wF=function(a){o7(this);var b=this.o.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}q7(this,!b);b&&i7(this.F,"Missed "+b+" lounge tokens.")};
g.h.vF=function(a){i7(this.F,"Requesting lounge tokens failed: "+a)};g.r(s7,g.Q);g.h=s7.prototype;g.h.start=function(){var a=parseInt(g.rs("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.I)()-144E5<a?0:a)?u7(this):(this.A=(0,g.I)()+3E5,g.qs("yt-remote-fast-check-period",this.A),this.ju())};
g.h.isEmpty=function(){return g.ec(this.o)};
g.h.update=function(){r7("Updating availability on schedule.");var a=this.C(),b=g.Sb(this.o,function(c,d){return c&&!!k6(a,d)},this);
t7(this,b)};
g.h.Y=function(){g.Lo(this.w);this.w=NaN;this.u&&(this.u.abort(),this.u=null);g.Q.prototype.Y.call(this)};
g.h.ju=function(){g.Lo(this.w);this.w=NaN;this.u&&this.u.abort();var a=bwa(this);if(a6(a)){var b=f7(this.B,"/pairing/get_screen_availability");this.u=g7(this.B,b,{lounge_token:g.Yb(a).join(",")},(0,g.x)(this.cN,this,a),(0,g.x)(this.bN,this))}else t7(this,{}),u7(this)};
g.h.cN=function(a,b){this.u=null;var c=g.Yb(bwa(this));if(g.vb(c,g.Yb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;t7(this,d);u7(this)}else this.Sb("Changing Screen set during request."),this.ju()};
g.h.bN=function(a){this.Sb("Screen availability failed: "+a);this.u=null;u7(this)};
g.h.Sb=function(a){i7("OnlineScreenService",a)};g.Ua(v7,m7);g.h=v7.prototype;g.h.start=function(){this.w.start();this.u.start();this.o.length&&(this.R("screenChange"),this.u.isEmpty()||this.R("onlineScreenChange"))};
g.h.add=function(a,b,c){this.w.add(a,b,c)};
g.h.remove=function(a,b,c){this.w.remove(a,b,c);this.u.update()};
g.h.Kp=function(a,b,c,d){this.w.contains(a)?this.w.Kp(a,b,c,d):(a="Updating name of unknown screen: "+a.name,i7(this.F,a),d(Error(a)))};
g.h.de=function(a){return a?this.o:g.jb(this.o,(0,g.ue)(this.A,function(b){return!this.contains(b)},this))};
g.h.aD=function(){return(0,g.ue)(this.de(!0),function(a){return!!this.u.o[a.id]},this)};
g.h.bD=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new n7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(k){g.Ge(f);d(w7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.Ge(f);e(k)});
f.start();return(0,g.x)(f.stop,f)};
g.h.MP=function(a,b,c,d){g.yp(f7(this.C,"/pairing/get_screen"),{method:"POST",zb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var k=new e6(f.screen||{});if(!k.name||fwa(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);fwa(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(w7(this,k))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
Od:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.h.Y=function(){g.Ge(this.w);g.Ge(this.u);v7.Gb.Y.call(this)};
g.h.EF=function(){gwa(this);this.R("screenChange");this.u.update()};
v7.prototype.dispose=v7.prototype.dispose;g.Ua(y7,g.Q);g.h=y7.prototype;g.h.Yo=function(a){this.w=a;this.R("sessionScreen",this.w)};
g.h.je=function(a){this.la()||(a&&z7(this,""+a),this.w=null,this.R("sessionScreen",null))};
g.h.info=function(a){i7(this.O,a)};
g.h.dD=function(){return null};
g.h.tu=function(a){var b=this.u;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){z7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.Y=function(){this.tu("");y7.Gb.Y.call(this)};g.Ua(A7,y7);g.h=A7.prototype;g.h.ru=function(a){if(this.o){if(this.o==a)return;z7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.C);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.o=a;this.o.addUpdateListener(this.C);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);iwa(this)};
g.h.rj=function(a){this.info("launchWithParams no-op for Cast: "+g.Lk(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.x)(function(){this.je()},this),(0,g.x)(function(){this.je(Error("Failed to stop receiver app."))},this)):this.je(Error("Stopping cast device witout session."))};
g.h.tu=g.Ja;g.h.Y=function(){this.info("disposeInternal");g.Lo(this.A);this.A=0;this.o&&(this.o.removeUpdateListener(this.C),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.o=null;A7.Gb.Y.call(this)};
g.h.XN=function(a,b){if(!this.la())if(b){var c=N6(b);if(g.Pa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Lk(c));switch(d){case "mdxSessionStatus":hwa(this,c.screenId);break;default:z7(this,"Unknown youtube message: "+d)}}else z7(this,"Unable to parse message.")}else z7(this,"No data in message.")};
g.h.Dx=function(a,b,c,d){ewa(this.H,this.u.label,a,this.u.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(z7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Jo((0,g.x)(this.Dx,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.dD=function(){return this.o};
g.h.NP=function(a){this.la()||a||(z7(this,"Cast session died."),this.je())};g.Ua(B7,y7);g.h=B7.prototype;g.h.ru=function(a){this.A=a;this.A.addUpdateListener(this.P)};
g.h.rj=function(a){this.B=a;this.F()};
g.h.stop=function(){this.o();this.o=g.Ja;g.Lo(this.C);this.A?this.A.stop((0,g.x)(this.je,this,null),(0,g.x)(this.je,this,"Failed to stop DIAL device.")):this.je()};
g.h.Y=function(){this.o();this.o=g.Ja;g.Lo(this.C);this.A&&this.A.removeUpdateListener(this.P);this.A=null;B7.Gb.Y.call(this)};
g.h.QP=function(a){this.la()||a||(z7(this,"DIAL session died."),this.o(),this.o=g.Ja,this.je())};
g.h.Qr=function(a){this.J=i6();if(this.B){var b=new chrome.cast.DialLaunchResponse(!0,kwa(this));a(b);jwa(this)}else this.F=(0,g.x)(function(){g.Lo(this.C);this.F=g.Ja;this.C=NaN;var c=new chrome.cast.DialLaunchResponse(!0,kwa(this));a(c);jwa(this)},this),this.C=g.Jo((0,g.x)(function(){this.F()},this),100)};
g.h.XF=function(a,b,c){ewa(this.H,this.G.receiver.label,a,this.u.friendlyName,(0,g.x)(function(d){d&&d.token?(this.Yo(d),b(new chrome.cast.DialLaunchResponse(!1))):this.Qr(b,c)},this),(0,g.x)(function(d){z7(this,"Failed to get DIAL screen: "+d);
this.Qr(b,c)},this))};g.Ua(C7,y7);C7.prototype.stop=function(){this.je()};
C7.prototype.ru=g.Ja;C7.prototype.rj=function(){g.Lo(this.o);this.o=NaN;var a=k6(this.H.de(),this.u.label);a?this.Yo(a):this.je(Error("No such screen"))};
C7.prototype.Y=function(){g.Lo(this.o);this.o=NaN;C7.Gb.Y.call(this)};g.Ua(D7,g.Q);g.h=D7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.F);this.G||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.JM,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.aB,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.ZK,this);chrome.cast.initialize(c,(0,g.x)(function(){this.la()||
(chrome.cast.addReceiverActionListener(this.A),Sva(),this.u.subscribe("onlineScreenChange",(0,g.x)(this.cD,this)),this.w=mwa(this),chrome.cast.setCustomReceivers(this.w,g.Ja,(0,g.x)(function(k){this.Sb("Failed to set initial custom receivers: "+g.Lk(k))},this)),this.R("yt-remote-cast2-availability-change",F7(this)),b(!0))},this),(0,g.x)(function(k){this.Sb("Failed to initialize API: "+g.Lk(k));
b(!1)},this))};
g.h.LO=function(a,b){E7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.w;if(!a||c&&c.id!=a)E7("Unsetting old screen status: "+this.o.u.friendlyName),G7(this,null)}if(a&&b){if(!this.o){c=k6(this.u.de(),a);if(!c){E7("setConnectedScreenStatus: Unknown screen.");return}var d=lwa(this,c);d||(E7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.w.push(d),chrome.cast.setCustomReceivers(this.w,
g.Ja,(0,g.x)(function(e){this.Sb("Failed to set initial custom receivers: "+g.Lk(e))},this)));
E7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);G7(this,new C7(this.u,d),!0)}this.o.tu(b)}else E7("setConnectedScreenStatus: no screen.")};
g.h.MO=function(a){this.la()?this.Sb("Setting connection data on disposed cast v2"):this.o?this.o.rj(a):this.Sb("Setting connection data without a session")};
g.h.PP=function(){this.la()?this.Sb("Stopping session on disposed cast v2"):this.o?(this.o.stop(),G7(this,null)):E7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.aB,this),(0,g.x)(this.gN,this))};
g.h.Y=function(){this.u.unsubscribe("onlineScreenChange",(0,g.x)(this.cD,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.A);var a=Pva,b=g.w("yt.mdx.remote.debug.handlers_");g.gb(b||[],a);g.Ge(this.o);D7.Gb.Y.call(this)};
g.h.Sb=function(a){i7("Controller",a)};
g.h.bB=function(a,b){this.o==a&&(b||G7(this,null),this.R("yt-remote-cast2-session-change",b))};
g.h.FM=function(a,b){if(!this.la())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),E7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.u.label!=a.label)E7("onReceiverAction_: Stopping active receiver: "+this.o.u.friendlyName),this.o.stop();else{E7("onReceiverAction_: Casting to active receiver.");this.o.w&&this.R("yt-remote-cast2-session-change",this.o.w);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:G7(this,
new C7(this.u,a));break;case chrome.cast.ReceiverType.DIAL:G7(this,new B7(this.u,a,this.C));break;case chrome.cast.ReceiverType.CAST:G7(this,new A7(this.u,a));break;default:this.Sb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.o&&this.o.u.label==a.label?this.o.stop():this.Sb("Stopping receiver w/o session: "+a.friendlyName)}else this.Sb("onReceiverAction_ called without receiver.")};
g.h.ZK=function(a){if(this.la())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Sb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.u:null;if(!c||c.label!=b.label)return this.Sb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.o.w)return E7("Reselecting dial screen."),
this.R("yt-remote-cast2-session-change",this.o.w),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Sb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);G7(this,new B7(this.u,b,this.C))}b=this.o;b.G=a;return b.G.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.XF,b,(b.G.extraData||{}).screenId||null)):new Promise((0,g.x)(b.Qr,b))};
g.h.aB=function(a){if(!this.la()){E7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==chrome.cast.ReceiverType.CAST)E7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),G7(this,new A7(this.u,b),!0);else{this.Sb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.u,d=k6(this.u.de(),c.label);d&&f6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(E7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Ge(this.o),this.o=new A7(this.u,b),this.o.subscribe("sessionScreen",(0,g.x)(this.bB,this,this.o)),this.o.rj(null));this.o.ru(a)}}};
g.h.OP=function(){return this.o?this.o.dD():null};
g.h.gN=function(a){this.la()||(this.Sb("Failed to estabilish a session: "+g.Lk(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&G7(this,null))};
g.h.JM=function(a){E7("Receiver availability updated: "+a);if(!this.la()){var b=F7(this);this.B=a==chrome.cast.ReceiverAvailability.AVAILABLE;F7(this)!=b&&this.R("yt-remote-cast2-availability-change",F7(this))}};
g.h.cD=function(){this.la()||(this.w=mwa(this),E7("Updating custom receivers: "+g.Lk(this.w)),chrome.cast.setCustomReceivers(this.w,g.Ja,(0,g.x)(function(){this.Sb("Failed to set custom receivers.")},this)),this.R("yt-remote-cast2-availability-change",F7(this)))};
D7.prototype.setLaunchParams=D7.prototype.MO;D7.prototype.setConnectedScreenStatus=D7.prototype.LO;D7.prototype.stopSession=D7.prototype.PP;D7.prototype.getCastSession=D7.prototype.OP;D7.prototype.requestSession=D7.prototype.requestSession;D7.prototype.init=D7.prototype.init;D7.prototype.dispose=D7.prototype.dispose;var M7=[];R7.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";S7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.rf=a.hasPrevious,this.hasNext=a.hasNext,this.F=a.playerTime,this.C=a.playerTimeAt,this.A=a.seekableStart,this.u=a.seekableEnd,this.G=a.duration,this.H=a.loadedTime,this.w=a.liveIngestionTime,this.B=
!isNaN(this.w))};
R7.prototype.isAdPlaying=function(){return 1081==this.playerState};
R7.prototype.getDuration=function(){return this.B?this.G+T7(this):this.G};
R7.prototype.clone=function(){return new R7(X7(this))};g.r(Z7,g.Q);g.h=Z7.prototype;g.h.play=function(){1==this.o?(this.u?this.u.play(null,g.Ja,e8(this,"play")):d8(this,"play"),c8(this,1,V7($7(this))),this.R("remotePlayerChange")):a8(this,this.play)};
g.h.pause=function(){1==this.o?(this.u?this.u.pause(null,g.Ja,e8(this,"pause")):d8(this,"pause"),c8(this,2,V7($7(this))),this.R("remotePlayerChange")):a8(this,this.pause)};
g.h.seekTo=function(a){if(1==this.o){if(this.u){var b=$7(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.u.seek(c,g.Ja,e8(this,"seekTo",{newTime:a}))}else d8(this,"seekTo",{newTime:a});c8(this,3,a);this.R("remotePlayerChange")}else a8(this,g.Sa(this.seekTo,a))};
g.h.stop=function(){if(1==this.o){this.u?this.u.stop(null,g.Ja,e8(this,"stopVideo")):d8(this,"stopVideo");var a=$7(this);a.index=-1;a.videoId="";S7(a);b8(this,a);this.R("remotePlayerChange")}else a8(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=$7(this);if(this.w){if(c.volume!=a){var d=Math.round(a)/100;this.w.setReceiverVolumeLevel(d,(0,g.x)(function(){i7("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.Sb("failed to set receiver volume.")},this))}c.muted!=b&&this.w.setReceiverMuted(b,(0,g.x)(function(){i7("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.Sb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);d8(this,"setVolume",e)}c.muted=b;c.volume=a;b8(this,c)}else a8(this,g.Sa(this.setVolume,a,b))};
g.h.bC=function(a,b){if(1==this.o){var c=$7(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Lk(b.style),g.kc(d,c.o));d8(this,"setSubtitlesTrack",d);b8(this,c)}else a8(this,g.Sa(this.bC,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.o){var c=b.getLanguageInfo().getId();d8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=$7(this);d.audioTrackId=c;b8(this,d)}else a8(this,g.Sa(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=$7(this);c=c||0;var m={videoId:a,currentIndex:c};W7(l,a,c);void 0!==b&&(U7(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Lk(k));d8(this,"setPlaylist",m);d||b8(this,l)};
g.h.YC=function(a,b){if(1==this.o){if(a&&b){var c=$7(this);W7(c,a,b);b8(this,c)}d8(this,"previous")}else a8(this,g.Sa(this.YC,a,b))};
g.h.nextVideo=function(a,b){if(1==this.o){if(a&&b){var c=$7(this);W7(c,a,b);b8(this,c)}d8(this,"next")}else a8(this,g.Sa(this.nextVideo,a,b))};
g.h.Mw=function(){1==this.o?d8(this,"dismissAutoplay"):a8(this,this.Mw)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.R("proxyStateChange",a,this.o)}g.Q.prototype.dispose.call(this)};
g.h.Y=function(){zwa(this);this.A=null;this.B.clear();Y7(this,null);g.Q.prototype.Y.call(this)};
g.h.Yu=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.R("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)b=a=this.B,g.db(b.o)&&(b.o=b.u,b.o.reverse(),b.u=[]),a.o.pop().apply(this);else 3==a&&this.dispose()}};
g.h.CM=function(a,b){this.R(a,b)};
g.h.GK=function(a){if(!a)this.Ll(null),Y7(this,null);else if(this.w.receiver.volume){a=this.w.receiver.volume;var b=$7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)i7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,b8(this,b)}};
g.h.Ll=function(a){i7("CP","Cast media: "+!!a);this.u&&this.u.removeUpdateListener(this.G);if(this.u=a)this.u.addUpdateListener(this.G),Awa(this),this.R("remotePlayerChange")};
g.h.FK=function(a){a?(Awa(this),this.R("remotePlayerChange")):this.Ll(null)};
g.h.RK=function(){var a=wwa();a&&Y7(this,a)};
g.h.Sb=function(a){i7("CP",a)};g.r(f8,g.Q);g.h=f8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==k&&(l.currentIndex=k);c&&(this.Ta.listId=c);this.Ta.videoId=d;this.Ta.index=k||0;this.Ta.state=3;U7(this.Ta,m);this.A="UNSUPPORTED";g8("Connecting with setPlaylist and params: "+g.Lk(l));this.o.connect({method:"setPlaylist",
params:g.Lk(l)},a,Nua())}else g8("Connecting without params"),this.o.connect({},a,Nua());Cwa(this)};
g.h.dispose=function(){this.la()||(this.R("beforeDispose"),h8(this,3));g.Q.prototype.dispose.call(this)};
g.h.Y=function(){i8(this);k8(this);j8(this);g.Lo(this.F);this.F=NaN;g.Lo(this.G);this.G=NaN;this.w=null;g.Iq(this.O);this.O.length=0;this.o.dispose();g.Q.prototype.Y.call(this);this.A=this.C=this.u=this.Ta=this.o=null};
g.h.oF=function(){this.Wi(2)};
g.h.KK=function(){g8("Channel opened");this.P&&(this.P=!1,j8(this),this.J=g.Jo((0,g.x)(function(){g8("Timing out waiting for a screen.");this.Wi(1)},this),15E3));
Rua(Mva(this.o),this.S)};
g.h.HK=function(){g8("Channel closed");isNaN(this.B)?q6(!0):q6();this.dispose()};
g.h.IK=function(a){q6();isNaN(this.Ik())?(g8("Channel error: "+a+" without reconnection"),this.dispose()):(this.P=!0,g8("Channel error: "+a+" with reconnection in "+this.Ik()+" ms"),h8(this,2))};
g.h.JK=function(a){a.params?g8("Received: action="+a.action+", params="+g.Lk(a.params)):g8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=N6(a.params.devices);this.u=(0,g.A)(a,function(c){return new d6(c)});
a=!!g.$a(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
Fwa(this,a);break;case "loungeScreenDisconnected":g.ib(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
Fwa(this,!1);break;case "remoteConnected":var b=new d6(N6(a.params.device));g.$a(this.u,function(c){return b?c.id==b.id:!1})||xua(this.u,b);
break;case "remoteDisconnected":b=new d6(N6(a.params.device));g.ib(this.u,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":Hwa(this,a);break;case "nowPlaying":Jwa(this,a);break;case "onStateChange":Iwa(this,a);break;case "onAdStateChange":Kwa(this,a);break;case "onVolumeChanged":Lwa(this,a);break;case "onSubtitlesTrackChanged":Gwa(this,a);break;case "nowAutoplaying":Mwa(this,a);break;case "autoplayDismissed":this.R("autoplayDismissed");break;case "autoplayUpNext":this.C=a.params.videoId||null;this.R("autoplayUpNext",this.C);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.R("autoplayModeChange",this.A);"DISABLED"==this.A&&this.R("autoplayDismissed");break;case "onHasPreviousNextChanged":Nwa(this,a);break;case "requestAssistedSignIn":this.R("assistedSignInRequested",a.params.authCode);break;default:g8("Unrecognized action: "+a.action)}};
g.h.zO=function(){if(this.w){var a=this.w;this.w=null;this.Ta.videoId!=a&&l8(this,"getNowPlaying")}};
g.h.dF=function(){var a=3;this.la()||(a=0,isNaN(this.Ik())?d7(this.o)&&isNaN(this.B)&&(a=1):a=2);return a};
g.h.Wi=function(a){g8("Disconnecting with "+a);i8(this);this.R("beforeDisconnect",a);1==a&&q6();Nva(this.o,a);this.dispose()};
g.h.cF=function(){var a=this.Ta;this.w&&(a=this.Ta.clone(),W7(a,this.w,a.index));return X7(a)};
g.h.NO=function(a){var b=new R7(a);b.videoId&&b.videoId!=this.Ta.videoId&&(this.w=b.videoId,g.Lo(this.F),this.F=g.Jo((0,g.x)(this.zO,this),5E3));var c=[];this.Ta.listId==b.listId&&this.Ta.videoId==b.videoId&&this.Ta.index==b.index||c.push("remoteQueueChange");this.Ta.playerState==b.playerState&&this.Ta.volume==b.volume&&this.Ta.muted==b.muted&&V7(this.Ta)==V7(b)&&g.Lk(this.Ta.o)==g.Lk(b.o)||c.push("remotePlayerChange");this.Ta.reset(a);(0,g.y)(c,function(d){this.R(d)},this)};
g.h.Bx=function(){var a=this.o.C.id,b=g.$a(this.u,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.Ik=function(){var a=this.o;return a.u.isActive()?a.u.u-(0,g.I)():NaN};
g.h.RE=function(){return this.A||"UNSUPPORTED"};
g.h.SE=function(){return this.C||""};
g.h.HP=function(){if(!isNaN(this.Ik())){var a=this.o.u;g.Bn(a.o);a.start()}};
g.h.IO=function(a,b){l8(this,a,b);Ewa(this)};
f8.prototype.subscribe=f8.prototype.subscribe;f8.prototype.unsubscribeByKey=f8.prototype.ug;f8.prototype.getProxyState=f8.prototype.dF;f8.prototype.disconnect=f8.prototype.Wi;f8.prototype.getPlayerContextData=f8.prototype.cF;f8.prototype.setPlayerContextData=f8.prototype.NO;f8.prototype.getOtherConnectedRemoteId=f8.prototype.Bx;f8.prototype.getReconnectTimeout=f8.prototype.Ik;f8.prototype.getAutoplayMode=f8.prototype.RE;f8.prototype.getAutoplayVideoId=f8.prototype.SE;f8.prototype.reconnect=f8.prototype.HP;
f8.prototype.sendMessage=f8.prototype.IO;g.r(m8,m7);g.h=m8.prototype;g.h.de=function(a){return this.rd.$_gs(a)};
g.h.contains=function(a){return!!this.rd.$_c(a)};
g.h.get=function(a){return this.rd.$_g(a)};
g.h.start=function(){this.rd.$_st()};
g.h.add=function(a,b,c){this.rd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.rd.$_r(a,b,c)};
g.h.Kp=function(a,b,c,d){this.rd.$_un(a,b,c,d)};
g.h.Y=function(){for(var a=0,b=this.u.length;a<b;++a)this.rd.$_ubk(this.u[a]);this.u.length=0;this.rd=null;m7.prototype.Y.call(this)};
g.h.LP=function(){this.R("screenChange")};
g.h.hM=function(){this.R("onlineScreenChange")};
v7.prototype.$_st=v7.prototype.start;v7.prototype.$_gspc=v7.prototype.MP;v7.prototype.$_gsppc=v7.prototype.bD;v7.prototype.$_c=v7.prototype.contains;v7.prototype.$_g=v7.prototype.get;v7.prototype.$_a=v7.prototype.add;v7.prototype.$_un=v7.prototype.Kp;v7.prototype.$_r=v7.prototype.remove;v7.prototype.$_gs=v7.prototype.de;v7.prototype.$_gos=v7.prototype.aD;v7.prototype.$_s=v7.prototype.subscribe;v7.prototype.$_ubk=v7.prototype.ug;var F8=null,E8=!1,n8=null,o8=null,D8=null,s8=[];g.r(G8,g.C);g.h=G8.prototype;
g.h.Y=function(){g.C.prototype.Y.call(this);this.A.stop();this.C.stop();this.P.stop();this.U();this.o.unsubscribe("proxyStateChange",this.XA,this);this.o.unsubscribe("remotePlayerChange",this.Pl,this);this.o.unsubscribe("remoteQueueChange",this.Zo,this);this.o.unsubscribe("autoplayUpNext",this.yA,this);this.o.unsubscribe("previousNextChange",this.UA,this);this.o.unsubscribe("nowAutoplaying",this.QA,this);this.o.unsubscribe("autoplayDismissed",this.xA,this);this.o=this.B=null};
g.h.yz=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.o.o)if(J8(this)){if(!$7(this.o).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==$7(this.o).playerState?this.o.pause():this.o.play();break;case "control_play":this.o.play();break;case "control_pause":this.o.pause();break;case "control_seek":this.J.Lx(c[0],c[1]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":c=c[0],J8(this)&&this.o.setAudioTrack(this.u.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.u.getCurrentTime();L8(this,0==c?void 0:c);break;case "control_seek":L8(this,c[0]);break;case "control_subtitles_set_track":K8(this,c[0]);break;case "control_set_audio_track":c=c[0],J8(this)&&this.o.setAudioTrack(this.u.getVideoData(1).videoId,c)}};
g.h.EK=function(a){this.P.kF(a)};
g.h.mP=function(a){this.yz("control_subtitles_set_track",g.ec(a)?null:a)};
g.h.pC=function(){var a=this.u.getOption("captions","track");g.ec(a)||K8(this,a)};
g.h.IA=function(a){if(J8(this)){this.o.unsubscribe("remotePlayerChange",this.Pl,this);var b=Math.round(a.volume);a=!!a.muted;var c=$7(this.o);if(b!=c.volume||a!=c.muted)this.o.setVolume(b,a),this.O.start();this.o.subscribe("remotePlayerChange",this.Pl,this)}};
g.h.DL=function(){g.ec(this.F)||Zwa(this,this.F);this.G=!1};
g.h.XA=function(a,b){this.C.stop();2==b&&this.oC()};
g.h.Pl=function(){if(J8(this)){this.A.stop();var a=$7(this.o);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.B.H=1;break;case 1082:case 1083:this.B.H=0;break;default:this.B.H=-1}switch(a.playerState){case 1081:case 1:I8(this,new g.rD(8));this.nC();break;case 1085:case 3:I8(this,new g.rD(9));break;case 1083:case 0:I8(this,new g.rD(2));this.J.stop();H8(this,this.u.getVideoData().lengthSeconds);break;case 1084:I8(this,new g.rD(4));break;case 2:I8(this,new g.rD(4));H8(this,V7(a));
break;case -1:I8(this,new g.rD(64));break;case -1E3:I8(this,new g.rD(128,{errorCode:"mdx.remoteerror",errorMessage:"Video ini tidak tersedia untuk pemutaran jarak jauh"}))}a=$7(this.o).o;var b=this.F;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.F=a,Zwa(this,a));a=$7(this.o);-1==a.volume||Math.round(this.u.getVolume())==a.volume&&this.u.isMuted()==a.muted||this.O.isActive()||this.NC()}else Ywa(this)};
g.h.UA=function(){this.u.R("mdxpreviousnextchange")};
g.h.Zo=function(){J8(this)||Ywa(this)};
g.h.fE=function(){this.o.Mw()};
g.h.yA=function(){};
g.h.QA=function(a){isNaN(a)||this.u.R("mdxnowautoplaying",a)};
g.h.xA=function(){this.u.R("mdxautoplaycanceled")};
g.h.gI=function(a,b){-1==$7(this.o).playerState?L8(this,a):b&&this.o.seekTo(a)};
g.h.NC=function(){if(J8(this)){var a=$7(this.o);this.w.Ya(this.S);a.muted?this.u.mute():this.u.unMute();this.u.setVolume(a.volume);this.S=this.w.L(this.u,"onVolumeChange",this.IA)}};
g.h.nC=function(){this.A.stop();if(!this.o.la()){var a=$7(this.o);1==a.playerState&&I8(this,new g.rD(8));H8(this,V7(a));this.A.start()}};
g.h.oC=function(){this.C.stop();this.A.stop();var a=this.o.A.getReconnectTimeout();2==this.o.o&&!isNaN(a)&&this.C.start()};g.r(M8,g.V);M8.prototype.w=function(){c6("mdx-privacy-popup-cancel");this.u.hide()};
M8.prototype.B=function(){c6("mdx-privacy-popup-confirm");this.u.hide()};g.r(N8,g.V);N8.prototype.A=function(a){axa(this,a.state)};g.r(O8,g.HO);O8.prototype.J=function(){var a=this.u.getOption("remote","receivers");a&&1<a.length&&!this.u.getOption("remote","quickCast")?(this.C=g.xb(a,this.B,this),g.JO(this,(0,g.A)(a,this.B)),a=this.u.getOption("remote","currentReceiver"),this.Fe(this.B(a)),this.enable(!0)):this.enable(!1)};
O8.prototype.B=function(a){return a.key};
O8.prototype.We=function(a){return"cast-selector-receiver"==a?"Transmisi...":this.C[a].name};
O8.prototype.Zc=function(a){g.HO.prototype.Zc.call(this,a);this.u.setOption("remote","currentReceiver",this.C[a]);this.w.nb()};g.r(P8,g.RP);g.h=P8.prototype;
g.h.create=function(){Swa(g.Bx(this.player.N()));this.A.push(g.Qo("yt-remote-before-disconnect",this.BK,this));this.A.push(g.Qo("yt-remote-connection-change",this.KM,this));this.A.push(g.Qo("yt-remote-receiver-availability-change",this.VA,this));this.A.push(g.Qo("yt-remote-auto-connect",this.IM,this));this.A.push(g.Qo("yt-remote-receiver-resumed",this.HM,this));this.A.push(g.Qo("mdx-privacy-popup-confirm",this.lO,this));this.A.push(g.Qo("mdx-privacy-popup-cancel",this.kO,this));this.VA()};
g.h.load=function(){this.player.cancelPlayback();g.RP.prototype.load.call(this);this.B=new G8(this,this.player,this.o);var a=(a=Xwa())?a.currentTime:0;var b=C8()?new Z7(x8(),void 0):null;0==a&&b&&(a=V7($7(b)));0!=a&&(this.O=a||0,this.player.R("progresssync",a,void 0));$wa(this,this.F,this.F);g.zT(this.player.app,6)};
g.h.unload=function(){this.player.R("mdxautoplaycanceled");this.w=this.u;g.He(this.B,this.o);this.o=this.B=null;g.RP.prototype.unload.call(this);g.zT(this.player.app,5);Q8(this)};
g.h.Y=function(){g.Ro(this.A);g.RP.prototype.Y.call(this)};
g.h.zl=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.yz.apply(this.B,[a].concat(g.na(c)))};
g.h.getAdState=function(){return this.H};
g.h.fF=function(){return this.loaded?this.B.suggestion:null};
g.h.rf=function(){return this.o?$7(this.o).rf:!1};
g.h.hasNext=function(){return this.o?$7(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.O};
g.h.getProgressState=function(){var a=$7(this.o),b=this.player.getVideoData();return{allowSeeking:g.R(this.player.N().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.Pc():!a.isAdPlaying()&&this.player.Pc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.B?a.w+T7(a):a.w,isAtLiveHead:1>=(a.B?a.u+T7(a):a.u)-this.getCurrentTime(),loaded:a.H,seekableEnd:a.B?a.u+T7(a):a.u,seekableStart:0<a.A?a.A+T7(a):
a.A}};
g.h.nextVideo=function(){this.o&&this.o.nextVideo()};
g.h.NH=function(){this.o&&this.o.YC()};
g.h.BK=function(a){1==a&&(this.S=this.o?$7(this.o):null)};
g.h.KM=function(){var a=C8()?new Z7(x8(),void 0):null;if(a){var b=this.w;this.loaded&&this.unload();this.o=a;this.S=null;b.key!=this.u.key&&(this.w=b,this.load())}else g.Ge(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.S)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,V7(a)));this.player.R("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.VA=function(){this.J=[this.u].concat(Uwa());var a=y8()||this.u;R8(this,a);this.player.ka("onMdxReceiversChange")};
g.h.cO=function(a){!this.P&&g.FD(a,8)&&(this.player.pauseVideo(),Q8(this))};
g.h.IM=function(){var a=y8();R8(this,a)};
g.h.HM=function(){this.w=y8()};
g.h.lO=function(){this.P=!0;Q8(this);E8=!1;F8&&A8(F8,1);F8=null};
g.h.kO=function(){this.P=!1;Q8(this);R8(this,this.u);this.w=this.u;E8=!1;F8=null;this.player.playVideo()};
g.h.Mc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.J;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?P7():R8(this,b)),this.loaded?this.w:this.u;case "quickCast":return 2==this.J.length&&"cast-selector-receiver"==this.J[1].key?(b&&P7(),!0):!1}};
g.h.OH=function(){d8(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Gf=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.fQ.remote=P8;})(_yt_player);
